name: Production installation tests using npm link to install
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.platform }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm link tx2uml --only=production
      - name: Chungo NFT call
        run: tx2uml 0x720e126ea17f4e0b2fcf021e6c6b90b55c5283527cdf50d4c2eb3cdbc012dbfc -v -p
        env:
          ARCHIVE_NODE_URL: ${{ secrets.ARCHIVE_NODE_URL }}
      - name: Chungo NFT value
        run: tx2uml value 0x720e126ea17f4e0b2fcf021e6c6b90b55c5283527cdf50d4c2eb3cdbc012dbfc -v
        env:
          ARCHIVE_NODE_URL: ${{ secrets.ARCHIVE_NODE_URL }}
